### ISSUE TITLE
 Unable to load asset: .git/HEAD

### ISSUE THREAD

**Issue by ibrhm-jz** [Rexios80/git_info#1]
When trying to load the folder with .git it shows me Unhandled Exception: Unable to load asset: .git/HEAD , 
I already changed the bleeding and testing with another project and nothing
My pubsbec.yaml
flutter:
  uses-material-design: true

  assets:
    - .git/HEAD
    - .git/refs/heads/
    - .git/refs/heads/feature/

**Comment by Rexios80** [comment]
You need to have a git repo in the root of the project. Does .git/HEAD exist in your project?

**Comment by ibrhm-jz** [comment]
correct, I already have an existing repository, I have found that other people have this same problem, would you know why?
https://www.gitmemory.com/issue/flutter/flutter/80957/825062557

**Comment by Rexios80** [comment]
Can you create a repository that reproduces the issue so I can look at it?

It works for me and all my coworkers so I really don't know what the issue is. I'm pretty sure `.git/HEAD` has to exist in a git repo.

**Comment by Rexios80** [comment]
Ohhhh you're saying the file exists but it doesn't load on Android. Does it work on iOS?

**Comment by Rexios80** [comment]
This is a bug with Flutter. I created an issue for it: https://github.com/flutter/flutter/issues/87200

**Comment by Rexios80** [comment]
I updated the readme with instructions on how to make it work for Android
