### ISSUE TITLE
Freshly cloned repo doesn't contains requred directories

### ISSUE THREAD

**Issue by Yuiry-IV** [Rexios80/git_info#2]
![image](https://user-images.githubusercontent.com/9569717/128312536-533ef2e9-e484-4730-b525-dd3c27912266.png)

Commands to reproduce 
```
git clone https://github.com/Yuiry-IV/flutter_git_info.git
cd flutter_git_info/
flutter pub get
flutter analyze
```

**Comment by Rexios80** [comment]
There's no way around that if you want to be able to show branch hashes, and it's a warning not an error. If you want the analysis issue to go away ignore it in your analysis options.

**Comment by Rexios80** [comment]
Perhaps a build script could be used instead but I haven't messed with those in dart
